### ISSUE TITLE
Quando a IA vira dama a peça não está virando de fato dama

### ISSUE THREAD

**Issue by vitornl** [vitornl/TCC00293-ES2#48]

**Comment by vitornl** [comment]
Quando ela come para trás no próprio lado do tabuleiro está virando dama

**Comment by VitorA29** [comment]
ela termina o movimento na posição de virar dama?

**Comment by VitorA29** [comment]
2 5
1 4
4 5
3 4
1 6
2 5
3 6
4 5
2 5
1 4
4 7
3 6

Caso de teste do bug
